# CircleCI configuration file

version: 2.1

jobs:
  build-test:
  docker:
    - image: 
  steps:
    - checkout
    - run: npm ci
    - run: npm run build
    - run: npm test


workflows:
  buildtest:
    jobs:
      - build-test
        filters:
          branches:
            only:
              -cirlceci