name: testWorkflow

on:
  push:
    branches:
      - "main"

jobs:
  echo:
    runs-on: ubuntu-latest

    steps:
      - name: hello world
        run: |
          export NAME=heh
          echo $NAME